Update patch set 8
Patch Set 8:

I have updated and merged patch https://gerrit.opnfv.org/gerrit/c/dovetail/+/68460.
You can rebase your patch to master locally.
For error "TypeError: 'dict_keys' object does not support indexing", with python3, d.keys() and d.values() returns a dict_keys object ranther than a list (with python2).
For error "AttributeError: 'dict' object has no attribute 'iteritems'", Python3 renames 'iteritems' to 'items'.
For error "TypeError: argument should be a str object or an os.PathLike object returning str, not <class 'mock.mock.MagicMock'>", Python3 renames '__builtin__' to 'builtins'.

Patch-set: 8
Label: Verified=0