Update patch set 10
Patch Set 10:

> Trying to run tox following error
 > ERROR: tox version is 2.3.1, required is at least 2.5
 > Please change the minimum version in tox file accordingly or remove
 > it if not needed.

Hi, this patch does not include any change to tox.ini file. Thus, if such a change is mandatory it should happen in another patch.

Furthermore, how did you install tox on your machine? The .deb and .rpm packages coming with ubuntu and centos distros contain old version of tox.

You can confirm it by running

$tox --version
(output from my machine: 3.5.3 imported from /usr/local/lib/python3.5/dist-packages/tox/__init__.py)

In order to install latest tox you should download and install it with pip. Of course, you should remove the one you installed through your distro package manager.

You should also consider that the same code passes jenkins jobs, which run tox.

Regards

Patch-set: 10