Update patch set 4
Patch Set 4: Code-Review-1

(1 comment)

I test it locally and failed with the reason
File "/usr/local/lib/python2.7/dist-packages/dovetail/run.py", line 256, in main
logger = dt_logger.Logger('run').getLogger()
File "/usr/local/lib/python2.7/dist-packages/dovetail/utils/dovetail_logger.py", line 41, in __init__
result_path = dt_cfg.dovetail_config['result_dir']
KeyError: 'result_dir'

Patch-set: 4